stages:          
  - test
  - linting

unit-test-job:   
  stage: test    
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest -v

flake8:
  stage: linting
  image: python:3.9
  before_script:
    - pip install flake8
  script:
    - flake8 --exclude=crypto_app --count > flake8_rapport.txt
  artifacts:
    paths:
        - flake8_rapport.txt
  allow_failure: true



