stages:          
  - test
  - linting

unit-test-job:   
  stage: test    
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest -v

flake8:
  stage: linting
  script:
    - flake8 --verbose .



