stages:          
  - test
  - linting

unit-test-job:   
  stage: test    
  script:
    - echo "Running unit tests."
    - pytest -v

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .



