stages:          
  - test
  - linting

unit-test-job:   
  stage: test    
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Running unit tests."
    - pytest -v

linting:
  stage: linting
  image: python:3.9
  script:
    - isort . 
    - black .
    - flake .
    - find . -type f -name "*.py" | xargs pylint

